// Anime Vanguards Units Database - Extended Edition
// Based on community tier lists and game data

export const unitsData = {
  "units": [
    // ====== EXISTING 16 UNITS ======
    {
      "id": "song-jinwu-monarch",
      "name": "Song Jinwu (Monarch)",
      "rarity": "Mythic",
      "element": "Unknown",
      "tier": "S",
      "placement_cost": "Medium",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": true,
      "pros": ["Multiple summons", "3 different nukes", "Good DPS and range", "Great placement, performs at all upgrades"],
      "cons": ["Nukes are 1 time use per game", "Needs mana to use summons/nukes"],
      "description": "Top summoner with unmatched DPS and synergy with Igros",
      "recommended_traits": ["Deadeye", "Damage Boost"],
      "anime_source": "Solo Leveling"
    },
    {
      "id": "akazo-destructive",
      "name": "Akazo (Destructive)",
      "rarity": "Mythic",
      "element": "Fire",
      "tier": "S+",
      "placement_cost": "High",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": true,
      "pros": ["Very high DPS", "2nd highest full AoE in game", "Not dependent on other units", "Scales great with crit"],
      "cons": ["Weak on placement until upgrade 2", "Not immune to debuffs or status effects"],
      "description": "Deals heavy damage with massive AoE capabilities",
      "recommended_traits": ["Deadeye", "Crit Damage"],
      "anime_source": "Demon Slayer"
    },
    {
      "id": "cha-in-blade-dancer",
      "name": "Cha-In (Blade Dancer)",
      "rarity": "Mythic",
      "element": "Physical",
      "tier": "S+",
      "placement_cost": "High",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": true,
      "pros": ["Incredible DPS numbers", "Can trigger transformation frequently", "100% crit strike potential"],
      "cons": ["Expensive to max", "Requires positioning"],
      "description": "Blade master with transformation abilities",
      "recommended_traits": ["Deadeye", "Speed Boost"],
      "anime_source": "Solo Leveling"
    },
    {
      "id": "divalo-requiem",
      "name": "Divalo (Requiem)",
      "rarity": "Secret",
      "element": "Time",
      "tier": "SS",
      "placement_cost": "Very High",
      "max_placement": 1,
      "category": "Support/DPS",
      "evolution_required": true,
      "pros": ["100% dodge chance", "Time Erasure ability", "Crowd control", "Unbreakable"],
      "cons": ["Very expensive", "Only 1 placement", "Hard to obtain"],
      "description": "The unbreakable king with time manipulation",
      "recommended_traits": ["Range", "Cooldown Reduction"],
      "anime_source": "JoJo's Bizarre Adventure"
    },
    {
      "id": "igros-elite-knight",
      "name": "Igros (Elite Knight)", 
      "rarity": "Secret",
      "element": "Dark",
      "tier": "SS",
      "placement_cost": "High",
      "max_placement": 3,
      "category": "DPS",
      "evolution_required": true,
      "pros": ["Synergy with Song Jinwu", "High damage output", "Elite summons"],
      "cons": ["Dependent on other units for max potential", "Expensive"],
      "description": "Elite knight with powerful dark abilities",
      "recommended_traits": ["Damage", "Range"],
      "anime_source": "Solo Leveling"
    },
    {
      "id": "alucard-vampire-king",
      "name": "Alucard (Vampire King)",
      "rarity": "Secret", 
      "element": "Blood",
      "tier": "S+",
      "placement_cost": "Medium",
      "max_placement": 4,
      "category": "Support/DPS",
      "evolution_required": false,
      "pros": ["Full AoE", "8 sec bleed", "20% buff to all source damage", "Cheap to upgrade"],
      "cons": ["Lower raw damage", "Bleed dependent"],
      "description": "Vampire lord with bleed and support abilities",
      "recommended_traits": ["Bleed Boost", "Range"],
      "anime_source": "Hellsing"
    },
    {
      "id": "jag-o-volcanic",
      "name": "Jag-o (Volcanic)",
      "rarity": "Mythic",
      "element": "Fire",
      "tier": "S",
      "placement_cost": "High",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": true,
      "pros": ["High damage AoE", "Burn effects", "Good for wave clearing"],
      "cons": ["Expensive", "Fire element limitations"],
      "description": "Fiery DPS beast with volcanic powers",
      "recommended_traits": ["Burn Damage", "AoE Boost"],
      "anime_source": "Jujutsu Kaisen"
    },
    {
      "id": "chaso-blood-curse",
      "name": "Chaso (Blood Curse)",
      "rarity": "Mythic", 
      "element": "Blood",
      "tier": "S",
      "placement_cost": "High",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": true,
      "pros": ["Full AoE attacks", "DMG boost vs bleeding enemies", "4 placements"],
      "cons": ["Requires bleeding enemies", "Complex setup"],
      "description": "Blood curse specialist with AoE devastation",
      "recommended_traits": ["Bleed", "Damage"],
      "anime_source": "Jujutsu Kaisen"
    },
    {
      "id": "hakura-rin-dancer",
      "name": "Hakura Rin (Dancer)",
      "rarity": "Legendary",
      "element": "Support",
      "tier": "A",
      "placement_cost": "Low",
      "max_placement": 6,
      "category": "Support",
      "evolution_required": false,
      "pros": ["18% ally damage buff", "10% range buff", "Accessible from battle pass"],
      "cons": ["No direct damage", "Requires other strong units"],
      "description": "Best support unit for enhancing team performance",
      "recommended_traits": ["Buff Duration", "Range"],
      "anime_source": "Hololive"
    },
    {
      "id": "super-brolzi",
      "name": "Legendary Super Brolzi",
      "rarity": "Legendary",
      "element": "Energy",
      "tier": "A",
      "placement_cost": "Medium",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": false,
      "pros": ["No evolution required", "High base damage", "AoE attacks", "Cost efficient"],
      "cons": ["Limited compared to mythics", "No evolution potential"],
      "description": "Powerful legendary that doesn't require evolution",
      "recommended_traits": ["Damage", "Speed"],
      "anime_source": "Dragon Ball"
    },
    {
      "id": "tengon-flashiness",
      "name": "Tengon (Flashiness)",
      "rarity": "Mythic",
      "element": "Physical",
      "tier": "A",
      "placement_cost": "High",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": true,
      "pros": ["AOE damage", "Massive range", "Good upgrade scaling"],
      "cons": ["High placement cost", "Requires evolution for full potential"],
      "description": "Deals AOE damage in massive range",
      "recommended_traits": ["Damage", "Range"],
      "anime_source": "Demon Slayer"
    },
    {
      "id": "noruto-six-tails",
      "name": "Noruto (Six Tails)",
      "rarity": "Mythic",
      "element": "Energy",
      "tier": "S",
      "placement_cost": "High",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": true,
      "pros": ["Great at clearing waves", "High damage output", "Good range"],
      "cons": ["Expensive to max", "Evolution dependent"],
      "description": "Powerful ninja with tailed beast chakra",
      "recommended_traits": ["Damage", "Speed"],
      "anime_source": "Naruto"
    },
    {
      "id": "obita-awakened",
      "name": "Obita (Awakened)",
      "rarity": "Mythic",
      "element": "Space",
      "tier": "S",
      "placement_cost": "High",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": true,
      "pros": ["Space-time abilities", "Good damage", "Utility skills"],
      "cons": ["Complex mechanics", "Requires positioning"],
      "description": "Awakened Uchiha with space-time mastery",
      "recommended_traits": ["Damage", "Cooldown"],
      "anime_source": "Naruto"
    },
    {
      "id": "sosuke-storm",
      "name": "Sosuke (Storm)",
      "rarity": "Mythic",
      "element": "Lightning",
      "tier": "A",
      "placement_cost": "Medium",
      "max_placement": 4,
      "category": "DPS/Support",
      "evolution_required": true,
      "pros": ["Stun abilities", "Double damage vs base form", "Good utility"],
      "cons": ["Situational abilities", "Requires good positioning"],
      "description": "Lightning-powered captain with stun abilities",
      "recommended_traits": ["Stun Duration", "Damage"],
      "anime_source": "Bleach"
    },
    {
      "id": "sprintwagon",
      "name": "Sprintwagon",
      "rarity": "Epic",
      "element": "Support",
      "tier": "A",
      "placement_cost": "Very Low",
      "max_placement": 8,
      "category": "Support",
      "evolution_required": false,
      "pros": ["Crazy ROI", "Very cheap", "Good support abilities", "High placement count"],
      "cons": ["No direct damage", "Support role only"],
      "description": "Only Epic unit in top tiers, amazing value",
      "recommended_traits": ["Buff Duration", "Range"],
      "anime_source": "JoJo's Bizarre Adventure"
    },
    {
      "id": "yehowach-almighty",
      "name": "Yehowach (Almighty)",
      "rarity": "Secret",
      "element": "Holy",
      "tier": "S",
      "placement_cost": "Very High",
      "max_placement": 2,
      "category": "Support/DPS",
      "evolution_required": false,
      "pros": ["Status immunity", "Buffs allies", "High damage", "Future sight abilities"],
      "cons": ["Very expensive", "Complex mechanics", "Limited placement"],
      "description": "Quincy king with almighty powers",
      "recommended_traits": ["Buff Duration", "Range"],
      "anime_source": "Bleach"
    },
    
    // ====== NEW SECRET TIER UNITS ======
    {
      "id": "gojo-infinity",
      "name": "Gojo (Infinity)",
      "rarity": "Secret",
      "element": "Space",
      "tier": "SS",
      "placement_cost": "Very High",
      "max_placement": 1,
      "category": "DPS/Support",
      "evolution_required": true,
      "pros": ["Infinity technique", "Domain expansion", "Teleportation", "Crowd control"],
      "cons": ["Very expensive", "Only 1 placement", "Complex mechanics"],
      "description": "The strongest sorcerer with infinity and domain powers",
      "recommended_traits": ["Range", "Cooldown Reduction"],
      "anime_source": "Jujutsu Kaisen"
    },
    {
      "id": "sukuna-king-curses",
      "name": "Sukuna (King of Curses)",
      "rarity": "Secret",
      "element": "Cursed",
      "tier": "S+",
      "placement_cost": "Very High",
      "max_placement": 2,
      "category": "DPS",
      "evolution_required": true,
      "pros": ["Cursed techniques", "High damage output", "Multiple abilities", "Strong AoE"],
      "cons": ["Very expensive", "Limited placement", "Complex setup"],
      "description": "The king of curses with devastating cursed techniques",
      "recommended_traits": ["Damage", "Cursed Boost"],
      "anime_source": "Jujutsu Kaisen"
    },
    {
      "id": "madara-ultimate",
      "name": "Madara (Ultimate)",
      "rarity": "Secret",
      "element": "Fire",
      "tier": "S+",
      "placement_cost": "Very High",
      "max_placement": 2,
      "category": "DPS",
      "evolution_required": true,
      "pros": ["Eternal Mangekyo", "Susanoo", "Fire release", "Crowd control"],
      "cons": ["Very expensive", "Limited placement", "Complex abilities"],
      "description": "The ultimate Uchiha with legendary powers",
      "recommended_traits": ["Damage", "Fire Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "whitebeard-prime",
      "name": "Whitebeard (Prime)",
      "rarity": "Secret",
      "element": "Quake",
      "tier": "S",
      "placement_cost": "Very High",
      "max_placement": 2,
      "category": "DPS/Tank",
      "evolution_required": true,
      "pros": ["Quake fruit", "High durability", "AoE damage", "Tank capabilities"],
      "cons": ["Very expensive", "Limited placement", "Slow movement"],
      "description": "The strongest man in the world with quake powers",
      "recommended_traits": ["Damage", "Tank Boost"],
      "anime_source": "One Piece"
    },
    
    // ====== NEW MYTHIC TIER UNITS ======
    {
      "id": "tanjiro-hinokami",
      "name": "Tanjiro (Hinokami)",
      "rarity": "Mythic",
      "element": "Fire",
      "tier": "S",
      "placement_cost": "High",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": true,
      "pros": ["Hinokami Kagura", "Sun breathing", "High damage", "Good range"],
      "cons": ["Expensive", "Fire element weakness", "Requires evolution"],
      "description": "Master of the legendary Hinokami Kagura technique",
      "recommended_traits": ["Damage", "Fire Boost"],
      "anime_source": "Demon Slayer"
    },
    {
      "id": "zenitsu-god-speed",
      "name": "Zenitsu (God Speed)",
      "rarity": "Mythic",
      "element": "Lightning",
      "tier": "S",
      "placement_cost": "High",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": true,
      "pros": ["Thunder breathing", "God speed", "High burst damage", "Fast attacks"],
      "cons": ["Expensive", "Lightning element weakness", "Complex mechanics"],
      "description": "Lightning-fast demon slayer with god speed abilities",
      "recommended_traits": ["Speed", "Lightning Boost"],
      "anime_source": "Demon Slayer"
    },
    {
      "id": "inosuke-beast-king",
      "name": "Inosuke (Beast King)",
      "rarity": "Mythic",
      "element": "Physical",
      "tier": "A",
      "placement_cost": "High",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": true,
      "pros": ["Beast breathing", "High physical damage", "Good AoE", "Tank capabilities"],
      "cons": ["Expensive", "Physical element weakness", "Limited range"],
      "description": "Beast breathing master with wild combat style",
      "recommended_traits": ["Damage", "Physical Boost"],
      "anime_source": "Demon Slayer"
    },
    {
      "id": "giyu-water-hashira",
      "name": "Giyu (Water Hashira)",
      "rarity": "Mythic",
      "element": "Water",
      "tier": "S",
      "placement_cost": "High",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": true,
      "pros": ["Water breathing", "Hashira power", "High damage", "Good utility"],
      "cons": ["Expensive", "Water element weakness", "Requires positioning"],
      "description": "Water Hashira with mastery of water breathing techniques",
      "recommended_traits": ["Damage", "Water Boost"],
      "anime_source": "Demon Slayer"
    },
    {
      "id": "shinobu-insect-hashira",
      "name": "Shinobu (Insect Hashira)",
      "rarity": "Mythic",
      "element": "Poison",
      "tier": "A",
      "placement_cost": "High",
      "max_placement": 4,
      "category": "DPS/Support",
      "evolution_required": true,
      "pros": ["Insect breathing", "Poison effects", "Support abilities", "Good utility"],
      "cons": ["Expensive", "Poison element weakness", "Lower damage"],
      "description": "Insect Hashira with poison and support capabilities",
      "recommended_traits": ["Poison", "Support Boost"],
      "anime_source": "Demon Slayer"
    },
    {
      "id": "kakashi-copy-ninja",
      "name": "Kakashi (Copy Ninja)",
      "rarity": "Mythic",
      "element": "Lightning",
      "tier": "S",
      "placement_cost": "High",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": true,
      "pros": ["Sharingan", "Lightning techniques", "High damage", "Versatile abilities"],
      "cons": ["Expensive", "Lightning element weakness", "Complex mechanics"],
      "description": "The Copy Ninja with Sharingan and lightning mastery",
      "recommended_traits": ["Damage", "Lightning Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "itachi-akatsuki",
      "name": "Itachi (Akatsuki)",
      "rarity": "Mythic",
      "element": "Fire",
      "tier": "S",
      "placement_cost": "High",
      "max_placement": 4,
      "category": "DPS",
      "pros": ["Mangekyo Sharingan", "Fire techniques", "Genjutsu", "High damage"],
      "cons": ["Expensive", "Fire element weakness", "Complex abilities"],
      "description": "Akatsuki member with Mangekyo Sharingan powers",
      "recommended_traits": ["Damage", "Fire Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "minato-yellow-flash",
      "name": "Minato (Yellow Flash)",
      "rarity": "Mythic",
      "element": "Space",
      "tier": "S",
      "placement_cost": "High",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": true,
      "pros": ["Flying Thunder God", "Space-time jutsu", "High damage", "Teleportation"],
      "cons": ["Expensive", "Space element weakness", "Complex positioning"],
      "description": "The Yellow Flash with space-time mastery",
      "recommended_traits": ["Damage", "Space Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "ace-fire-fist",
      "name": "Ace (Fire Fist)",
      "rarity": "Mythic",
      "element": "Fire",
      "tier": "A",
      "placement_cost": "High",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": true,
      "pros": ["Fire fruit", "High fire damage", "Good AoE", "Logia immunity"],
      "cons": ["Expensive", "Fire element weakness", "Limited utility"],
      "description": "Fire Fist Ace with Logia devil fruit powers",
      "recommended_traits": ["Damage", "Fire Boost"],
      "anime_source": "One Piece"
    },
    {
      "id": "luffy-gear-5",
      "name": "Luffy (Gear 5)",
      "rarity": "Mythic",
      "element": "Physical",
      "tier": "S+",
      "placement_cost": "High",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": true,
      "pros": ["Gear 5 transformation", "High damage", "Good AoE", "Versatile abilities"],
      "cons": ["Expensive", "Physical element weakness", "Complex mechanics"],
      "description": "Straw Hat captain in his ultimate Gear 5 form",
      "recommended_traits": ["Damage", "Physical Boost"],
      "anime_source": "One Piece"
    },
    {
      "id": "zoro-king-hell",
      "name": "Zoro (King of Hell)",
      "rarity": "Mythic",
      "element": "Physical",
      "tier": "S",
      "placement_cost": "High",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": true,
      "pros": ["King of Hell", "High damage", "Good range", "Sword mastery"],
      "cons": ["Expensive", "Physical element weakness", "Limited AoE"],
      "description": "The King of Hell with ultimate sword techniques",
      "recommended_traits": ["Damage", "Physical Boost"],
      "anime_source": "One Piece"
    },
    {
      "id": "ichigo-bankai",
      "name": "Ichigo (Bankai)",
      "rarity": "Mythic",
      "element": "Soul",
      "tier": "S",
      "placement_cost": "High",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": true,
      "pros": ["Bankai form", "High damage", "Good range", "Soul reaper powers"],
      "cons": ["Expensive", "Soul element weakness", "Complex abilities"],
      "description": "Soul Reaper with Bankai transformation",
      "recommended_traits": ["Damage", "Soul Boost"],
      "anime_source": "Bleach"
    },
    {
      "id": "aizen-sosuke",
      "name": "Aizen (Sosuke)",
      "rarity": "Mythic",
      "element": "Illusion",
      "tier": "S",
      "placement_cost": "High",
      "max_placement": 4,
      "category": "DPS/Support",
      "evolution_required": true,
      "pros": ["Kyoka Suigetsu", "Illusion powers", "High damage", "Crowd control"],
      "cons": ["Expensive", "Illusion element weakness", "Complex mechanics"],
      "description": "Master manipulator with illusion and hypnosis powers",
      "recommended_traits": ["Damage", "Illusion Boost"],
      "anime_source": "Bleach"
    },
    {
      "id": "yoruichi-thunder-god",
      "name": "Yoruichi (Thunder God)",
      "rarity": "Mythic",
      "element": "Lightning",
      "tier": "A",
      "placement_cost": "High",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": true,
      "pros": ["Thunder God form", "High speed", "Good damage", "Utility skills"],
      "cons": ["Expensive", "Lightning element weakness", "Limited AoE"],
      "description": "Thunder God with lightning-fast combat abilities",
      "recommended_traits": ["Speed", "Lightning Boost"],
      "anime_source": "Bleach"
    },
    
    // ====== NEW LEGENDARY TIER UNITS ======
    {
      "id": "naruto-sage-mode",
      "name": "Naruto (Sage Mode)",
      "rarity": "Legendary",
      "element": "Nature",
      "tier": "A",
      "placement_cost": "Medium",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": false,
      "pros": ["Sage mode", "Nature chakra", "Good damage", "No evolution needed"],
      "cons": ["Medium cost", "Nature element weakness", "Limited utility"],
      "description": "Naruto in powerful Sage Mode",
      "recommended_traits": ["Damage", "Nature Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "sasuke-curse-mark",
      "name": "Sasuke (Curse Mark)",
      "rarity": "Legendary",
      "element": "Lightning",
      "tier": "A",
      "placement_cost": "Medium",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": false,
      "pros": ["Curse mark", "Lightning techniques", "Good damage", "No evolution needed"],
      "cons": ["Medium cost", "Lightning element weakness", "Limited AoE"],
      "description": "Sasuke with curse mark powers",
      "recommended_traits": ["Damage", "Lightning Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "sakura-medical-ninja",
      "name": "Sakura (Medical Ninja)",
      "rarity": "Legendary",
      "element": "Support",
      "tier": "A",
      "placement_cost": "Low",
      "max_placement": 6,
      "category": "Support",
      "evolution_required": false,
      "pros": ["Medical jutsu", "Healing abilities", "Good support", "High placement"],
      "cons": ["No direct damage", "Support role only", "Requires allies"],
      "description": "Medical ninja with healing and support abilities",
      "recommended_traits": ["Healing", "Support Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "sanji-black-leg",
      "name": "Sanji (Black Leg)",
      "rarity": "Legendary",
      "element": "Fire",
      "tier": "A",
      "placement_cost": "Medium",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": false,
      "pros": ["Black leg style", "Fire kicks", "Good damage", "No evolution needed"],
      "cons": ["Medium cost", "Fire element weakness", "Limited range"],
      "description": "Black Leg Sanji with fire-powered kicks",
      "recommended_traits": ["Damage", "Fire Boost"],
      "anime_source": "One Piece"
    },
    {
      "id": "nami-weather-witch",
      "name": "Nami (Weather Witch)",
      "rarity": "Legendary",
      "element": "Weather",
      "tier": "A",
      "placement_cost": "Medium",
      "max_placement": 4,
      "category": "DPS/Support",
      "evolution_required": false,
      "pros": ["Weather control", "Lightning attacks", "Good utility", "No evolution needed"],
      "cons": ["Medium cost", "Weather element weakness", "Lower damage"],
      "description": "Weather witch with climate control abilities",
      "recommended_traits": ["Weather", "Utility Boost"],
      "anime_source": "One Piece"
    },
    {
      "id": "usopp-sniper-king",
      "name": "Usopp (Sniper King)",
      "rarity": "Legendary",
      "element": "Physical",
      "tier": "B",
      "placement_cost": "Medium",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": false,
      "pros": ["Sniper skills", "Long range", "Good utility", "No evolution needed"],
      "cons": ["Medium cost", "Physical element weakness", "Lower damage"],
      "description": "Sniper King with long-range combat abilities",
      "recommended_traits": ["Range", "Utility Boost"],
      "anime_source": "One Piece"
    },
    {
      "id": "chopper-monster-point",
      "name": "Chopper (Monster Point)",
      "rarity": "Legendary",
      "element": "Physical",
      "tier": "B",
      "placement_cost": "Medium",
      "max_placement": 4,
      "category": "DPS/Tank",
      "evolution_required": false,
      "pros": ["Monster point", "High durability", "Good damage", "No evolution needed"],
      "cons": ["Medium cost", "Physical element weakness", "Limited utility"],
      "description": "Monster Point Chopper with enhanced combat abilities",
      "recommended_traits": ["Damage", "Tank Boost"],
      "anime_source": "One Piece"
    },
    {
      "id": "robin-demonic",
      "name": "Robin (Demonic)",
      "rarity": "Legendary",
      "element": "Physical",
      "tier": "B",
      "placement_cost": "Medium",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": false,
      "pros": ["Devil fruit", "Multiple limbs", "Good utility", "No evolution needed"],
      "cons": ["Medium cost", "Physical element weakness", "Lower damage"],
      "description": "Demonic Robin with devil fruit powers",
      "recommended_traits": ["Utility", "Physical Boost"],
      "anime_source": "One Piece"
    },
    {
      "id": "franky-cyborg",
      "name": "Franky (Cyborg)",
      "rarity": "Legendary",
      "element": "Physical",
      "tier": "B",
      "placement_cost": "Medium",
      "max_placement": 4,
      "category": "DPS/Tank",
      "evolution_required": false,
      "pros": ["Cyborg body", "High durability", "Good damage", "No evolution needed"],
      "cons": ["Medium cost", "Physical element weakness", "Limited utility"],
      "description": "Cyborg Franky with mechanical enhancements",
      "recommended_traits": ["Damage", "Tank Boost"],
      "anime_source": "One Piece"
    },
    {
      "id": "brook-soul-king",
      "name": "Brook (Soul King)",
      "rarity": "Legendary",
      "element": "Soul",
      "tier": "B",
      "placement_cost": "Medium",
      "max_placement": 4,
      "category": "DPS",
      "evolution_required": false,
      "pros": ["Soul powers", "Musical abilities", "Good utility", "No evolution needed"],
      "cons": ["Medium cost", "Soul element weakness", "Lower damage"],
      "description": "Soul King Brook with musical soul powers",
      "recommended_traits": ["Utility", "Soul Boost"],
      "anime_source": "One Piece"
    },
    
    // ====== NEW EPIC TIER UNITS ======
    {
      "id": "kiba-inuzuka",
      "name": "Kiba (Inuzuka)",
      "rarity": "Epic",
      "element": "Physical",
      "tier": "B",
      "placement_cost": "Low",
      "max_placement": 6,
      "category": "DPS",
      "evolution_required": false,
      "pros": ["Beast companion", "Good damage", "Low cost", "High placement"],
      "cons": ["Physical element weakness", "Limited utility", "Basic abilities"],
      "description": "Inuzuka clan member with beast companion",
      "recommended_traits": ["Damage", "Physical Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "shino-aburame",
      "name": "Shino (Aburame)",
      "rarity": "Epic",
      "element": "Insect",
      "tier": "B",
      "placement_cost": "Low",
      "max_placement": 6,
      "category": "DPS",
      "evolution_required": false,
      "pros": ["Insect control", "Good utility", "Low cost", "High placement"],
      "cons": ["Insect element weakness", "Lower damage", "Basic abilities"],
      "description": "Aburame clan member with insect control",
      "recommended_traits": ["Utility", "Insect Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "hinata-hyuuga",
      "name": "Hinata (Hyuuga)",
      "rarity": "Epic",
      "element": "Physical",
      "tier": "B",
      "placement_cost": "Low",
      "max_placement": 6,
      "category": "DPS",
      "evolution_required": false,
      "pros": ["Byakugan", "Good damage", "Low cost", "High placement"],
      "cons": ["Physical element weakness", "Limited utility", "Basic abilities"],
      "description": "Hyuuga clan member with Byakugan",
      "recommended_traits": ["Damage", "Physical Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "shikamaru-nara",
      "name": "Shikamaru (Nara)",
      "rarity": "Epic",
      "element": "Shadow",
      "tier": "B",
      "placement_cost": "Low",
      "max_placement": 6,
      "category": "DPS/Support",
      "evolution_required": false,
      "pros": ["Shadow techniques", "Good utility", "Low cost", "High placement"],
      "cons": ["Shadow element weakness", "Lower damage", "Basic abilities"],
      "description": "Nara clan member with shadow techniques",
      "recommended_traits": ["Utility", "Shadow Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "ino-yamanaka",
      "name": "Ino (Yamanaka)",
      "rarity": "Epic",
      "element": "Support",
      "tier": "B",
      "placement_cost": "Low",
      "max_placement": 6,
      "category": "Support",
      "evolution_required": false,
      "pros": ["Mind transfer", "Good support", "Low cost", "High placement"],
      "cons": ["No direct damage", "Support role only", "Basic abilities"],
      "description": "Yamanaka clan member with mind transfer",
      "recommended_traits": ["Support", "Utility Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "choji-akimichi",
      "name": "Choji (Akimichi)",
      "rarity": "Epic",
      "element": "Physical",
      "tier": "B",
      "placement_cost": "Low",
      "max_placement": 6,
      "category": "DPS/Tank",
      "evolution_required": false,
      "pros": ["Expansion jutsu", "Good tank", "Low cost", "High placement"],
      "cons": ["Physical element weakness", "Limited utility", "Basic abilities"],
      "description": "Akimichi clan member with expansion techniques",
      "recommended_traits": ["Tank", "Physical Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "kankuro-puppet-master",
      "name": "Kankuro (Puppet Master)",
      "rarity": "Epic",
      "element": "Physical",
      "tier": "B",
      "placement_cost": "Low",
      "max_placement": 6,
      "category": "DPS",
      "evolution_required": false,
      "pros": ["Puppet control", "Good utility", "Low cost", "High placement"],
      "cons": ["Physical element weakness", "Lower damage", "Basic abilities"],
      "description": "Puppet master with mechanical puppets",
      "recommended_traits": ["Utility", "Physical Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "temari-wind-master",
      "name": "Temari (Wind Master)",
      "rarity": "Epic",
      "element": "Wind",
      "tier": "B",
      "placement_cost": "Low",
      "max_placement": 6,
      "category": "DPS",
      "evolution_required": false,
      "pros": ["Wind techniques", "Good damage", "Low cost", "High placement"],
      "cons": ["Wind element weakness", "Limited utility", "Basic abilities"],
      "description": "Wind master with powerful wind techniques",
      "recommended_traits": ["Damage", "Wind Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "gaara-sand",
      "name": "Gaara (Sand)",
      "rarity": "Epic",
      "element": "Earth",
      "tier": "B",
      "placement_cost": "Low",
      "max_placement": 6,
      "category": "DPS",
      "evolution_required": false,
      "pros": ["Sand control", "Good damage", "Low cost", "High placement"],
      "cons": ["Earth element weakness", "Limited utility", "Basic abilities"],
      "description": "Sand user with sand manipulation abilities",
      "recommended_traits": ["Damage", "Earth Boost"],
      "anime_source": "Naruto"
    },
    
    // ====== NEW RARE TIER UNITS ======
    {
      "id": "konohamaru-sarutobi",
      "name": "Konohamaru (Sarutobi)",
      "rarity": "Rare",
      "element": "Wind",
      "tier": "C",
      "placement_cost": "Very Low",
      "max_placement": 8,
      "category": "DPS",
      "evolution_required": false,
      "pros": ["Wind techniques", "Very cheap", "High placement", "Easy to obtain"],
      "cons": ["Low damage", "Basic abilities", "Wind element weakness"],
      "description": "Young Sarutobi clan member with wind chakra",
      "recommended_traits": ["Damage", "Wind Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "moegi-uzumaki",
      "name": "Moegi (Uzumaki)",
      "rarity": "Rare",
      "element": "Wood",
      "tier": "C",
      "placement_cost": "Very Low",
      "max_placement": 8,
      "category": "DPS",
      "evolution_required": false,
      "pros": ["Wood release", "Very cheap", "High placement", "Easy to obtain"],
      "cons": ["Low damage", "Basic abilities", "Wood element weakness"],
      "description": "Uzumaki clan member with wood release",
      "recommended_traits": ["Damage", "Wood Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "udon-iwabee",
      "name": "Udon (Iwabee)",
      "rarity": "Rare",
      "element": "Physical",
      "tier": "C",
      "placement_cost": "Very Low",
      "max_placement": 8,
      "category": "DPS",
      "evolution_required": false,
      "pros": ["Physical techniques", "Very cheap", "High placement", "Easy to obtain"],
      "cons": ["Low damage", "Basic abilities", "Physical element weakness"],
      "description": "Physical combat specialist with basic techniques",
      "recommended_traits": ["Damage", "Physical Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "tenten-weapon-master",
      "name": "Tenten (Weapon Master)",
      "rarity": "Rare",
      "element": "Physical",
      "tier": "C",
      "placement_cost": "Very Low",
      "max_placement": 8,
      "category": "DPS",
      "evolution_required": false,
      "pros": ["Weapon mastery", "Very cheap", "High placement", "Easy to obtain"],
      "cons": ["Low damage", "Basic abilities", "Physical element weakness"],
      "description": "Weapon master with various combat tools",
      "recommended_traits": ["Damage", "Physical Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "rock-lee-youth",
      "name": "Rock Lee (Youth)",
      "rarity": "Rare",
      "element": "Physical",
      "tier": "C",
      "placement_cost": "Very Low",
      "max_placement": 8,
      "category": "DPS",
      "evolution_required": false,
      "pros": ["Taijutsu mastery", "Very cheap", "High placement", "Easy to obtain"],
      "cons": ["Low damage", "Basic abilities", "Physical element weakness"],
      "description": "Young taijutsu master with incredible speed",
      "recommended_traits": ["Speed", "Physical Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "neji-hyuuga-genin",
      "name": "Neji (Hyuuga Genin)",
      "rarity": "Rare",
      "element": "Physical",
      "tier": "C",
      "placement_cost": "Very Low",
      "max_placement": 8,
      "category": "DPS",
      "evolution_required": false,
      "pros": ["Byakugan", "Very cheap", "High placement", "Easy to obtain"],
      "cons": ["Low damage", "Basic abilities", "Physical element weakness"],
      "description": "Young Hyuuga prodigy with Byakugan",
      "recommended_traits": ["Damage", "Physical Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "kiba-inuzuka-genin",
      "name": "Kiba (Inuzuka Genin)",
      "rarity": "Rare",
      "element": "Physical",
      "tier": "C",
      "placement_cost": "Very Low",
      "max_placement": 8,
      "category": "DPS",
      "evolution_required": false,
      "pros": ["Beast companion", "Very cheap", "High placement", "Easy to obtain"],
      "cons": ["Low damage", "Basic abilities", "Physical element weakness"],
      "description": "Young Inuzuka with basic beast techniques",
      "recommended_traits": ["Damage", "Physical Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "shino-aburame-genin",
      "name": "Shino (Aburame Genin)",
      "rarity": "Rare",
      "element": "Insect",
      "tier": "C",
      "placement_cost": "Very Low",
      "max_placement": 8,
      "category": "DPS",
      "evolution_required": false,
      "pros": ["Insect control", "Very cheap", "High placement", "Easy to obtain"],
      "cons": ["Low damage", "Basic abilities", "Insect element weakness"],
      "description": "Young Aburame with basic insect techniques",
      "recommended_traits": ["Utility", "Insect Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "hinata-hyuuga-genin",
      "name": "Hinata (Hyuuga Genin)",
      "rarity": "Rare",
      "element": "Physical",
      "tier": "C",
      "placement_cost": "Very Low",
      "max_placement": 8,
      "category": "DPS",
      "evolution_required": false,
      "pros": ["Byakugan", "Very cheap", "High placement", "Easy to obtain"],
      "cons": ["Low damage", "Basic abilities", "Physical element weakness"],
      "description": "Young Hyuuga with basic Byakugan",
      "recommended_traits": ["Damage", "Physical Boost"],
      "anime_source": "Naruto"
    },
    {
      "id": "shikamaru-nara-genin",
      "name": "Shikamaru (Nara Genin)",
      "rarity": "Rare",
      "element": "Shadow",
      "tier": "C",
      "placement_cost": "Very Low",
      "max_placement": 8,
      "category": "DPS",
      "evolution_required": false,
      "pros": ["Shadow techniques", "Very cheap", "High placement", "Easy to obtain"],
      "cons": ["Low damage", "Basic abilities", "Shadow element weakness"],
      "description": "Young Nara with basic shadow techniques",
      "recommended_traits": ["Utility", "Shadow Boost"],
      "anime_source": "Naruto"
    }
  ],
  "tiers": {
    "SS": {
      "description": "Absolute best units, game-changing power",
      "color": "#ff6b6b"
    },
    "S+": {
      "description": "Extremely powerful, meta-defining units", 
      "color": "#ff8e53"
    },
    "S": {
      "description": "Very strong units, highly recommended",
      "color": "#ff6b9d"
    },
    "A": {
      "description": "Good units, solid choices for most content",
      "color": "#4ecdc4"
    },
    "B": {
      "description": "Average units, usable but not optimal",
      "color": "#45b7d1"
    },
    "C": {
      "description": "Basic units, good for beginners and early game",
      "color": "#95a5a6"
    }
  },
  "rarities": {
    "Vanguard": {"color": "#9b59b6", "chance": "0.005%"},
    "Secret": {"color": "#e74c3c", "chance": "0.1%"},
    "Mythic": {"color": "#f39c12", "chance": "1%"},
    "Legendary": {"color": "#3498db", "chance": "3.5%"},
    "Epic": {"color": "#9b59b6", "chance": "20%"},
    "Rare": {"color": "#2ecc71", "chance": "75.495%"}
  }
};
